# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="ba8d760a-a881-4d13-b0b8-03c656c2d5a5"

# Отправлять уведомление на почт уyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - onewaykd@gmail.com
    on_success: never # default: change
    on_failure: always # default: always